# Generated by Django 5.1.2 on 2024-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherdata_icon_alter_weatherdata_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweathersummary',
            name='icon_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
