# Generated by Django 5.1.2 on 2024-10-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_dailyweathersummary_icon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyweathersummary',
            old_name='icon_id',
            new_name='icon',
        ),
    ]
